/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithUserRouteImport } from './routes/_with-user'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WithUserAppIndexRouteImport } from './routes/_with-user/app/index'
import { Route as ApiAuthSignUpRouteImport } from './routes/api/auth/sign-up'
import { Route as ApiAuthSignInRouteImport } from './routes/api/auth/sign-in'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'

const WithUserRoute = WithUserRouteImport.update({
  id: '/_with-user',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WithUserAppIndexRoute = WithUserAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => WithUserRoute,
} as any)
const ApiAuthSignUpRoute = ApiAuthSignUpRouteImport.update({
  id: '/api/auth/sign-up',
  path: '/api/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignInRoute = ApiAuthSignInRouteImport.update({
  id: '/api/auth/sign-in',
  path: '/api/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/auth/sign-up': typeof ApiAuthSignUpRoute
  '/app/': typeof WithUserAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/auth/sign-up': typeof ApiAuthSignUpRoute
  '/app': typeof WithUserAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_with-user': typeof WithUserRouteWithChildren
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/auth/sign-up': typeof ApiAuthSignUpRoute
  '/_with-user/app/': typeof WithUserAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/auth/callback'
    | '/api/auth/sign-in'
    | '/api/auth/sign-up'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/auth/callback'
    | '/api/auth/sign-in'
    | '/api/auth/sign-up'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_with-user'
    | '/api/auth/callback'
    | '/api/auth/sign-in'
    | '/api/auth/sign-up'
    | '/_with-user/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WithUserRoute: typeof WithUserRouteWithChildren
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthSignInRoute: typeof ApiAuthSignInRoute
  ApiAuthSignUpRoute: typeof ApiAuthSignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_with-user': {
      id: '/_with-user'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WithUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_with-user/app/': {
      id: '/_with-user/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof WithUserAppIndexRouteImport
      parentRoute: typeof WithUserRoute
    }
    '/api/auth/sign-up': {
      id: '/api/auth/sign-up'
      path: '/api/auth/sign-up'
      fullPath: '/api/auth/sign-up'
      preLoaderRoute: typeof ApiAuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-in': {
      id: '/api/auth/sign-in'
      path: '/api/auth/sign-in'
      fullPath: '/api/auth/sign-in'
      preLoaderRoute: typeof ApiAuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface WithUserRouteChildren {
  WithUserAppIndexRoute: typeof WithUserAppIndexRoute
}

const WithUserRouteChildren: WithUserRouteChildren = {
  WithUserAppIndexRoute: WithUserAppIndexRoute,
}

const WithUserRouteWithChildren = WithUserRoute._addFileChildren(
  WithUserRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WithUserRoute: WithUserRouteWithChildren,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthSignInRoute: ApiAuthSignInRoute,
  ApiAuthSignUpRoute: ApiAuthSignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
