/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithoutUserRouteImport } from './routes/_without-user'
import { Route as WithUserRouteImport } from './routes/_with-user'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WithoutUserSignUpIndexRouteImport } from './routes/_without-user/sign-up/index'
import { Route as WithoutUserSignInIndexRouteImport } from './routes/_without-user/sign-in/index'
import { Route as WithUserAppIndexRouteImport } from './routes/_with-user/app/index'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'

const WithoutUserRoute = WithoutUserRouteImport.update({
  id: '/_without-user',
  getParentRoute: () => rootRouteImport,
} as any)
const WithUserRoute = WithUserRouteImport.update({
  id: '/_with-user',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WithoutUserSignUpIndexRoute = WithoutUserSignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => WithoutUserRoute,
} as any)
const WithoutUserSignInIndexRoute = WithoutUserSignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => WithoutUserRoute,
} as any)
const WithUserAppIndexRoute = WithUserAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => WithUserRoute,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/app/': typeof WithUserAppIndexRoute
  '/sign-in/': typeof WithoutUserSignInIndexRoute
  '/sign-up/': typeof WithoutUserSignUpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/app': typeof WithUserAppIndexRoute
  '/sign-in': typeof WithoutUserSignInIndexRoute
  '/sign-up': typeof WithoutUserSignUpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_with-user': typeof WithUserRouteWithChildren
  '/_without-user': typeof WithoutUserRouteWithChildren
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/_with-user/app/': typeof WithUserAppIndexRoute
  '/_without-user/sign-in/': typeof WithoutUserSignInIndexRoute
  '/_without-user/sign-up/': typeof WithoutUserSignUpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/auth/callback' | '/app/' | '/sign-in/' | '/sign-up/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/auth/callback' | '/app' | '/sign-in' | '/sign-up'
  id:
    | '__root__'
    | '/'
    | '/_with-user'
    | '/_without-user'
    | '/api/auth/callback'
    | '/_with-user/app/'
    | '/_without-user/sign-in/'
    | '/_without-user/sign-up/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WithUserRoute: typeof WithUserRouteWithChildren
  WithoutUserRoute: typeof WithoutUserRouteWithChildren
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_without-user': {
      id: '/_without-user'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WithoutUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_with-user': {
      id: '/_with-user'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WithUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_without-user/sign-up/': {
      id: '/_without-user/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof WithoutUserSignUpIndexRouteImport
      parentRoute: typeof WithoutUserRoute
    }
    '/_without-user/sign-in/': {
      id: '/_without-user/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof WithoutUserSignInIndexRouteImport
      parentRoute: typeof WithoutUserRoute
    }
    '/_with-user/app/': {
      id: '/_with-user/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof WithUserAppIndexRouteImport
      parentRoute: typeof WithUserRoute
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface WithUserRouteChildren {
  WithUserAppIndexRoute: typeof WithUserAppIndexRoute
}

const WithUserRouteChildren: WithUserRouteChildren = {
  WithUserAppIndexRoute: WithUserAppIndexRoute,
}

const WithUserRouteWithChildren = WithUserRoute._addFileChildren(
  WithUserRouteChildren,
)

interface WithoutUserRouteChildren {
  WithoutUserSignInIndexRoute: typeof WithoutUserSignInIndexRoute
  WithoutUserSignUpIndexRoute: typeof WithoutUserSignUpIndexRoute
}

const WithoutUserRouteChildren: WithoutUserRouteChildren = {
  WithoutUserSignInIndexRoute: WithoutUserSignInIndexRoute,
  WithoutUserSignUpIndexRoute: WithoutUserSignUpIndexRoute,
}

const WithoutUserRouteWithChildren = WithoutUserRoute._addFileChildren(
  WithoutUserRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WithUserRoute: WithUserRouteWithChildren,
  WithoutUserRoute: WithoutUserRouteWithChildren,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
