/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithoutUserRouteImport } from './routes/_without-user'
import { Route as WithUserRouteImport } from './routes/_with-user'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WithoutUserGetStartedIndexRouteImport } from './routes/_without-user/get-started/index'
import { Route as WithUserAppIndexRouteImport } from './routes/_with-user/app/index'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'

const WithoutUserRoute = WithoutUserRouteImport.update({
  id: '/_without-user',
  getParentRoute: () => rootRouteImport,
} as any)
const WithUserRoute = WithUserRouteImport.update({
  id: '/_with-user',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WithoutUserGetStartedIndexRoute =
  WithoutUserGetStartedIndexRouteImport.update({
    id: '/get-started/',
    path: '/get-started/',
    getParentRoute: () => WithoutUserRoute,
  } as any)
const WithUserAppIndexRoute = WithUserAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => WithUserRoute,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/app/': typeof WithUserAppIndexRoute
  '/get-started/': typeof WithoutUserGetStartedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/app': typeof WithUserAppIndexRoute
  '/get-started': typeof WithoutUserGetStartedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_with-user': typeof WithUserRouteWithChildren
  '/_without-user': typeof WithoutUserRouteWithChildren
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/_with-user/app/': typeof WithUserAppIndexRoute
  '/_without-user/get-started/': typeof WithoutUserGetStartedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/auth/callback' | '/app/' | '/get-started/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/auth/callback' | '/app' | '/get-started'
  id:
    | '__root__'
    | '/'
    | '/_with-user'
    | '/_without-user'
    | '/api/auth/callback'
    | '/_with-user/app/'
    | '/_without-user/get-started/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WithUserRoute: typeof WithUserRouteWithChildren
  WithoutUserRoute: typeof WithoutUserRouteWithChildren
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_without-user': {
      id: '/_without-user'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WithoutUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_with-user': {
      id: '/_with-user'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WithUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_without-user/get-started/': {
      id: '/_without-user/get-started/'
      path: '/get-started'
      fullPath: '/get-started/'
      preLoaderRoute: typeof WithoutUserGetStartedIndexRouteImport
      parentRoute: typeof WithoutUserRoute
    }
    '/_with-user/app/': {
      id: '/_with-user/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof WithUserAppIndexRouteImport
      parentRoute: typeof WithUserRoute
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface WithUserRouteChildren {
  WithUserAppIndexRoute: typeof WithUserAppIndexRoute
}

const WithUserRouteChildren: WithUserRouteChildren = {
  WithUserAppIndexRoute: WithUserAppIndexRoute,
}

const WithUserRouteWithChildren = WithUserRoute._addFileChildren(
  WithUserRouteChildren,
)

interface WithoutUserRouteChildren {
  WithoutUserGetStartedIndexRoute: typeof WithoutUserGetStartedIndexRoute
}

const WithoutUserRouteChildren: WithoutUserRouteChildren = {
  WithoutUserGetStartedIndexRoute: WithoutUserGetStartedIndexRoute,
}

const WithoutUserRouteWithChildren = WithoutUserRoute._addFileChildren(
  WithoutUserRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WithUserRoute: WithUserRouteWithChildren,
  WithoutUserRoute: WithoutUserRouteWithChildren,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
